name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            name: windows-amd64
            ext: .exe
          - goos: darwin
            goarch: amd64
            name: macos-intel
            ext: ""
          - goos: darwin
            goarch: arm64
            name: macos-arm64
            ext: ""
          - goos: linux
            goarch: amd64
            name: linux-amd64
            ext: ""
          - goos: linux
            goarch: arm64
            name: linux-arm64
            ext: ""
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go build -ldflags="-s -w" -o thunderbird-ai-compose-server-${{ matrix.name }}${{ matrix.ext }} .
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: thunderbird-ai-compose-server-${{ matrix.name }}${{ matrix.ext }}